blank_issues_enabled: false
contact_links:
  - name: â“ Ask a Question
    url: https://github.com/alshedivat//discussions/categories/q-a
    about: Ask and answer  related questions.
  - name: ğŸ“– Read the documentation
    url: https://github.com/alshedivat//blob/master/README.md
    about: Please consult the documentation before opening any issues!
